/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GravityERC721Interface extends ethers.utils.Interface {
  functions: {
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "sendERC721ToCosmos(address,string,uint256)": FunctionFragment;
    "state_gravitySolAddress()": FunctionFragment;
    "state_lastERC721EventNonce()": FunctionFragment;
    "withdrawERC721(address,uint256[],address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendERC721ToCosmos",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "state_gravitySolAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "state_lastERC721EventNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC721",
    values: [string, BigNumberish[], string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendERC721ToCosmos",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "state_gravitySolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "state_lastERC721EventNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC721",
    data: BytesLike
  ): Result;

  events: {
    "SendERC721ToCosmosEvent(address,address,string,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SendERC721ToCosmosEvent"): EventFragment;
}

export class GravityERC721 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GravityERC721Interface;

  functions: {
    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sendERC721ToCosmos(
      _tokenContract: string,
      _destination: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sendERC721ToCosmos(address,string,uint256)"(
      _tokenContract: string,
      _destination: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    state_gravitySolAddress(overrides?: CallOverrides): Promise<[string]>;

    "state_gravitySolAddress()"(overrides?: CallOverrides): Promise<[string]>;

    state_lastERC721EventNonce(overrides?: CallOverrides): Promise<[BigNumber]>;

    "state_lastERC721EventNonce()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawERC721(
      _ERC721TokenContract: string,
      _tokenIds: BigNumberish[],
      _destinations: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawERC721(address,uint256[],address[])"(
      _ERC721TokenContract: string,
      _tokenIds: BigNumberish[],
      _destinations: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  onERC721Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onERC721Received(address,address,uint256,bytes)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sendERC721ToCosmos(
    _tokenContract: string,
    _destination: string,
    _tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sendERC721ToCosmos(address,string,uint256)"(
    _tokenContract: string,
    _destination: string,
    _tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  state_gravitySolAddress(overrides?: CallOverrides): Promise<string>;

  "state_gravitySolAddress()"(overrides?: CallOverrides): Promise<string>;

  state_lastERC721EventNonce(overrides?: CallOverrides): Promise<BigNumber>;

  "state_lastERC721EventNonce()"(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawERC721(
    _ERC721TokenContract: string,
    _tokenIds: BigNumberish[],
    _destinations: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawERC721(address,uint256[],address[])"(
    _ERC721TokenContract: string,
    _tokenIds: BigNumberish[],
    _destinations: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    sendERC721ToCosmos(
      _tokenContract: string,
      _destination: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "sendERC721ToCosmos(address,string,uint256)"(
      _tokenContract: string,
      _destination: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    state_gravitySolAddress(overrides?: CallOverrides): Promise<string>;

    "state_gravitySolAddress()"(overrides?: CallOverrides): Promise<string>;

    state_lastERC721EventNonce(overrides?: CallOverrides): Promise<BigNumber>;

    "state_lastERC721EventNonce()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawERC721(
      _ERC721TokenContract: string,
      _tokenIds: BigNumberish[],
      _destinations: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawERC721(address,uint256[],address[])"(
      _ERC721TokenContract: string,
      _tokenIds: BigNumberish[],
      _destinations: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    SendERC721ToCosmosEvent(
      _tokenContract: string | null,
      _sender: string | null,
      _destination: null,
      _tokenId: null,
      _eventNonce: null
    ): EventFilter;
  };

  estimateGas: {
    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sendERC721ToCosmos(
      _tokenContract: string,
      _destination: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sendERC721ToCosmos(address,string,uint256)"(
      _tokenContract: string,
      _destination: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    state_gravitySolAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "state_gravitySolAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    state_lastERC721EventNonce(overrides?: CallOverrides): Promise<BigNumber>;

    "state_lastERC721EventNonce()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawERC721(
      _ERC721TokenContract: string,
      _tokenIds: BigNumberish[],
      _destinations: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawERC721(address,uint256[],address[])"(
      _ERC721TokenContract: string,
      _tokenIds: BigNumberish[],
      _destinations: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sendERC721ToCosmos(
      _tokenContract: string,
      _destination: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sendERC721ToCosmos(address,string,uint256)"(
      _tokenContract: string,
      _destination: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    state_gravitySolAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "state_gravitySolAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    state_lastERC721EventNonce(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "state_lastERC721EventNonce()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawERC721(
      _ERC721TokenContract: string,
      _tokenIds: BigNumberish[],
      _destinations: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawERC721(address,uint256[],address[])"(
      _ERC721TokenContract: string,
      _tokenIds: BigNumberish[],
      _destinations: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
