/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SigningTestInterface extends ethers.utils.Interface {
  functions: {
    "checkSignature(address,bytes32,uint8,bytes32,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkSignature",
    values: [string, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkSignature",
    data: BytesLike
  ): Result;

  events: {};
}

export class SigningTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SigningTestInterface;

  functions: {
    checkSignature(
      _signer: string,
      _theHash: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "checkSignature(address,bytes32,uint8,bytes32,bytes32)"(
      _signer: string,
      _theHash: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  checkSignature(
    _signer: string,
    _theHash: BytesLike,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkSignature(address,bytes32,uint8,bytes32,bytes32)"(
    _signer: string,
    _theHash: BytesLike,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    checkSignature(
      _signer: string,
      _theHash: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkSignature(address,bytes32,uint8,bytes32,bytes32)"(
      _signer: string,
      _theHash: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkSignature(
      _signer: string,
      _theHash: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkSignature(address,bytes32,uint8,bytes32,bytes32)"(
      _signer: string,
      _theHash: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkSignature(
      _signer: string,
      _theHash: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkSignature(address,bytes32,uint8,bytes32,bytes32)"(
      _signer: string,
      _theHash: BytesLike,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
