// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: launchpad/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateProjectRequest struct {
	// owner of this project
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	// the title of project
	ProjectTitle string `protobuf:"bytes,2,opt,name=project_title,json=projectTitle,proto3" json:"project_title,omitempty" yaml:"project_title"`
	// Project information
	ProjectInformation string `protobuf:"bytes,3,opt,name=project_information,json=projectInformation,proto3" json:"project_information,omitempty" yaml:"project_information"`
	// Begin time for a project
	StartTime time.Time `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
}

func (m *MsgCreateProjectRequest) Reset()         { *m = MsgCreateProjectRequest{} }
func (m *MsgCreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCreateProjectRequest) ProtoMessage()    {}
func (*MsgCreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f494aa6bbbad3607, []int{0}
}
func (m *MsgCreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateProjectRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateProjectRequest.Merge(m, src)
}
func (m *MsgCreateProjectRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateProjectRequest proto.InternalMessageInfo

func (m *MsgCreateProjectRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgCreateProjectRequest) GetProjectTitle() string {
	if m != nil {
		return m.ProjectTitle
	}
	return ""
}

func (m *MsgCreateProjectRequest) GetProjectInformation() string {
	if m != nil {
		return m.ProjectInformation
	}
	return ""
}

func (m *MsgCreateProjectRequest) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

type MsgCreateProjectResponse struct {
	ProjectId uint64 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" yaml:"project_id"`
}

func (m *MsgCreateProjectResponse) Reset()         { *m = MsgCreateProjectResponse{} }
func (m *MsgCreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateProjectResponse) ProtoMessage()    {}
func (*MsgCreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f494aa6bbbad3607, []int{1}
}
func (m *MsgCreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateProjectResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateProjectResponse.Merge(m, src)
}
func (m *MsgCreateProjectResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateProjectResponse proto.InternalMessageInfo

func (m *MsgCreateProjectResponse) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

type MsgDeleteProjectRequest struct {
	// owner of this project
	Owner     string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	ProjectId uint64 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" yaml:"project_id"`
}

func (m *MsgDeleteProjectRequest) Reset()         { *m = MsgDeleteProjectRequest{} }
func (m *MsgDeleteProjectRequest) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteProjectRequest) ProtoMessage()    {}
func (*MsgDeleteProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f494aa6bbbad3607, []int{2}
}
func (m *MsgDeleteProjectRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteProjectRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteProjectRequest.Merge(m, src)
}
func (m *MsgDeleteProjectRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteProjectRequest proto.InternalMessageInfo

func (m *MsgDeleteProjectRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgDeleteProjectRequest) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

type MsgDeleteProjectResponse struct {
}

func (m *MsgDeleteProjectResponse) Reset()         { *m = MsgDeleteProjectResponse{} }
func (m *MsgDeleteProjectResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteProjectResponse) ProtoMessage()    {}
func (*MsgDeleteProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f494aa6bbbad3607, []int{3}
}
func (m *MsgDeleteProjectResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteProjectResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteProjectResponse.Merge(m, src)
}
func (m *MsgDeleteProjectResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteProjectResponse proto.InternalMessageInfo

type MsgModifyStartTimeRequest struct {
	// owner of this project
	Owner     string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	ProjectId uint64 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" yaml:"project_id"`
	// Begin time for a project
	StartTime time.Time `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
}

func (m *MsgModifyStartTimeRequest) Reset()         { *m = MsgModifyStartTimeRequest{} }
func (m *MsgModifyStartTimeRequest) String() string { return proto.CompactTextString(m) }
func (*MsgModifyStartTimeRequest) ProtoMessage()    {}
func (*MsgModifyStartTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f494aa6bbbad3607, []int{4}
}
func (m *MsgModifyStartTimeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgModifyStartTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgModifyStartTimeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgModifyStartTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgModifyStartTimeRequest.Merge(m, src)
}
func (m *MsgModifyStartTimeRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgModifyStartTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgModifyStartTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgModifyStartTimeRequest proto.InternalMessageInfo

func (m *MsgModifyStartTimeRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgModifyStartTimeRequest) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *MsgModifyStartTimeRequest) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

type MsgModifyStartTimeResponse struct {
}

func (m *MsgModifyStartTimeResponse) Reset()         { *m = MsgModifyStartTimeResponse{} }
func (m *MsgModifyStartTimeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgModifyStartTimeResponse) ProtoMessage()    {}
func (*MsgModifyStartTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f494aa6bbbad3607, []int{5}
}
func (m *MsgModifyStartTimeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgModifyStartTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgModifyStartTimeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgModifyStartTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgModifyStartTimeResponse.Merge(m, src)
}
func (m *MsgModifyStartTimeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgModifyStartTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgModifyStartTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgModifyStartTimeResponse proto.InternalMessageInfo

type MsgModifyProjectInformationRequest struct {
	// owner of this project
	Owner     string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	ProjectId uint64 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" yaml:"project_id"`
	// Project information
	ProjectInformation string `protobuf:"bytes,3,opt,name=project_information,json=projectInformation,proto3" json:"project_information,omitempty" yaml:"project_information"`
}

func (m *MsgModifyProjectInformationRequest) Reset()         { *m = MsgModifyProjectInformationRequest{} }
func (m *MsgModifyProjectInformationRequest) String() string { return proto.CompactTextString(m) }
func (*MsgModifyProjectInformationRequest) ProtoMessage()    {}
func (*MsgModifyProjectInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f494aa6bbbad3607, []int{6}
}
func (m *MsgModifyProjectInformationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgModifyProjectInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgModifyProjectInformationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgModifyProjectInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgModifyProjectInformationRequest.Merge(m, src)
}
func (m *MsgModifyProjectInformationRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgModifyProjectInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgModifyProjectInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgModifyProjectInformationRequest proto.InternalMessageInfo

func (m *MsgModifyProjectInformationRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgModifyProjectInformationRequest) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *MsgModifyProjectInformationRequest) GetProjectInformation() string {
	if m != nil {
		return m.ProjectInformation
	}
	return ""
}

type MsgModifyProjectInformationResponse struct {
}

func (m *MsgModifyProjectInformationResponse) Reset()         { *m = MsgModifyProjectInformationResponse{} }
func (m *MsgModifyProjectInformationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgModifyProjectInformationResponse) ProtoMessage()    {}
func (*MsgModifyProjectInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f494aa6bbbad3607, []int{7}
}
func (m *MsgModifyProjectInformationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgModifyProjectInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgModifyProjectInformationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgModifyProjectInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgModifyProjectInformationResponse.Merge(m, src)
}
func (m *MsgModifyProjectInformationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgModifyProjectInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgModifyProjectInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgModifyProjectInformationResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateProjectRequest)(nil), "notionallabs.anone.launchpad.MsgCreateProjectRequest")
	proto.RegisterType((*MsgCreateProjectResponse)(nil), "notionallabs.anone.launchpad.MsgCreateProjectResponse")
	proto.RegisterType((*MsgDeleteProjectRequest)(nil), "notionallabs.anone.launchpad.MsgDeleteProjectRequest")
	proto.RegisterType((*MsgDeleteProjectResponse)(nil), "notionallabs.anone.launchpad.MsgDeleteProjectResponse")
	proto.RegisterType((*MsgModifyStartTimeRequest)(nil), "notionallabs.anone.launchpad.MsgModifyStartTimeRequest")
	proto.RegisterType((*MsgModifyStartTimeResponse)(nil), "notionallabs.anone.launchpad.MsgModifyStartTimeResponse")
	proto.RegisterType((*MsgModifyProjectInformationRequest)(nil), "notionallabs.anone.launchpad.MsgModifyProjectInformationRequest")
	proto.RegisterType((*MsgModifyProjectInformationResponse)(nil), "notionallabs.anone.launchpad.MsgModifyProjectInformationResponse")
}

func init() { proto.RegisterFile("launchpad/tx.proto", fileDescriptor_f494aa6bbbad3607) }

var fileDescriptor_f494aa6bbbad3607 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xcd, 0x24, 0xf9, 0x3e, 0x29, 0x43, 0x23, 0x60, 0x28, 0xc2, 0x58, 0xc5, 0xae, 0x06, 0x81,
	0xba, 0xc1, 0x46, 0xe5, 0x57, 0x48, 0x48, 0x10, 0xd8, 0x80, 0x14, 0x11, 0x99, 0x2e, 0x10, 0x1b,
	0x34, 0x49, 0x26, 0xae, 0x91, 0xed, 0x31, 0x9e, 0x89, 0xda, 0x6c, 0xba, 0xe2, 0x01, 0xfa, 0x06,
	0x3c, 0x00, 0x12, 0xcf, 0xd1, 0x65, 0x25, 0x36, 0xac, 0x0c, 0x4a, 0xde, 0x20, 0x4f, 0x80, 0x3c,
	0x13, 0xc7, 0x75, 0x9a, 0x94, 0x14, 0xaa, 0xee, 0x3c, 0xf7, 0xef, 0xdc, 0x73, 0xe6, 0xde, 0x31,
	0x44, 0x3e, 0xe9, 0x87, 0x9d, 0xed, 0x88, 0x74, 0x6d, 0xb1, 0x6b, 0x45, 0x31, 0x13, 0x0c, 0xad,
	0x85, 0x4c, 0x78, 0x2c, 0x24, 0xbe, 0x4f, 0xda, 0xdc, 0x22, 0x21, 0x0b, 0xa9, 0x35, 0x0d, 0xd3,
	0x4d, 0x97, 0x31, 0xd7, 0xa7, 0xb6, 0x8c, 0x6d, 0xf7, 0x7b, 0xb6, 0xf0, 0x02, 0xca, 0x05, 0x09,
	0x22, 0x95, 0xae, 0xaf, 0xba, 0xcc, 0x65, 0xf2, 0xd3, 0x4e, 0xbf, 0x94, 0x15, 0x7f, 0x2d, 0xc3,
	0x6b, 0x4d, 0xee, 0xbe, 0x88, 0x29, 0x11, 0xb4, 0x15, 0xb3, 0x8f, 0xb4, 0x23, 0x1c, 0xfa, 0xa9,
	0x4f, 0xb9, 0x40, 0xb7, 0xe1, 0x7f, 0x6c, 0x27, 0xa4, 0xb1, 0x06, 0xd6, 0xc1, 0x46, 0xad, 0x71,
	0x69, 0x9c, 0x98, 0x2b, 0x03, 0x12, 0xf8, 0x4f, 0xb0, 0x34, 0x63, 0x47, 0xb9, 0xd1, 0x53, 0x58,
	0x8f, 0x54, 0xe6, 0x07, 0xe1, 0x09, 0x9f, 0x6a, 0x65, 0x19, 0xaf, 0x8d, 0x13, 0x73, 0x55, 0xc5,
	0x17, 0xdc, 0xd8, 0x59, 0x99, 0x9c, 0xb7, 0xd2, 0x23, 0x7a, 0x03, 0xaf, 0x64, 0x7e, 0x2f, 0xec,
	0xb1, 0x38, 0x20, 0x29, 0x4d, 0xad, 0x22, 0x8b, 0x18, 0xe3, 0xc4, 0xd4, 0x8b, 0x45, 0x8e, 0x04,
	0x61, 0x07, 0x4d, 0xac, 0xaf, 0x72, 0x23, 0x7a, 0x07, 0x21, 0x17, 0x24, 0x4e, 0xe1, 0x02, 0xaa,
	0x55, 0xd7, 0xc1, 0xc6, 0x85, 0x4d, 0xdd, 0x52, 0xfa, 0x58, 0x99, 0x3e, 0xd6, 0x56, 0xa6, 0x4f,
	0xe3, 0xc6, 0x41, 0x62, 0x96, 0xc6, 0x89, 0x79, 0x59, 0xe1, 0xe4, 0xb9, 0x78, 0xff, 0xa7, 0x09,
	0x9c, 0x9a, 0x34, 0xa4, 0xe1, 0xb8, 0x05, 0xb5, 0xe3, 0x62, 0xf1, 0x88, 0x85, 0x9c, 0xa2, 0xfb,
	0x10, 0x4e, 0x3b, 0xec, 0x4a, 0xc9, 0xaa, 0x8d, 0xab, 0x79, 0xd5, 0xdc, 0x87, 0x9d, 0x5a, 0xd6,
	0x74, 0x17, 0xef, 0x48, 0xf9, 0x5f, 0x52, 0x9f, 0xfe, 0xb5, 0xfc, 0x45, 0xe0, 0xf2, 0x92, 0xc0,
	0xba, 0xa4, 0x32, 0x03, 0xac, 0xa8, 0xe0, 0xef, 0x00, 0x5e, 0x6f, 0x72, 0xb7, 0xc9, 0xba, 0x5e,
	0x6f, 0xf0, 0x36, 0x63, 0x7f, 0x2e, 0x7d, 0xcd, 0x5c, 0x5e, 0xe5, 0x0c, 0x2f, 0x6f, 0x0d, 0xea,
	0xf3, 0x48, 0xe5, 0x9c, 0xf1, 0xd4, 0xdd, 0x3a, 0x36, 0x54, 0xe7, 0x43, 0xfe, 0xac, 0x57, 0x01,
	0xdf, 0x82, 0x37, 0x4f, 0x24, 0xa5, 0xc8, 0x6f, 0x7e, 0xab, 0xc2, 0x4a, 0x93, 0xbb, 0x68, 0x0f,
	0xd6, 0x0b, 0xc3, 0x8d, 0x1e, 0x58, 0x27, 0x3d, 0x3a, 0xd6, 0x82, 0x97, 0x43, 0x7f, 0x78, 0xda,
	0xb4, 0xc9, 0x0e, 0xed, 0xc1, 0x7a, 0x61, 0x22, 0x97, 0xc0, 0x9f, 0xb7, 0x3a, 0x4b, 0xe0, 0xcf,
	0x1d, 0x7c, 0xf4, 0x19, 0xc0, 0x8b, 0x33, 0x03, 0x82, 0x1e, 0xfd, 0xb1, 0xd6, 0xfc, 0x3d, 0xd1,
	0x1f, 0x9f, 0x3e, 0x71, 0xd2, 0xc6, 0x17, 0x00, 0xb5, 0x45, 0x77, 0x86, 0x9e, 0x2d, 0x59, 0x76,
	0xe1, 0x0c, 0xeb, 0xcf, 0xff, 0xa1, 0x82, 0xea, 0xb0, 0xf1, 0xfa, 0x60, 0x68, 0x80, 0xc3, 0xa1,
	0x01, 0x7e, 0x0d, 0x0d, 0xb0, 0x3f, 0x32, 0x4a, 0x87, 0x23, 0xa3, 0xf4, 0x63, 0x64, 0x94, 0xde,
	0xdf, 0x75, 0x3d, 0xb1, 0xdd, 0x6f, 0x5b, 0x1d, 0x16, 0xd8, 0x19, 0xcc, 0x9d, 0x14, 0xc7, 0x96,
	0x38, 0xf6, 0xae, 0x7d, 0xe4, 0xd7, 0x36, 0x88, 0x28, 0x6f, 0xff, 0x2f, 0xb7, 0xfa, 0xde, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xec, 0xa7, 0x71, 0xf4, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateProject(ctx context.Context, in *MsgCreateProjectRequest, opts ...grpc.CallOption) (*MsgCreateProjectResponse, error)
	DeleteProject(ctx context.Context, in *MsgDeleteProjectRequest, opts ...grpc.CallOption) (*MsgDeleteProjectResponse, error)
	ModifyStartTime(ctx context.Context, in *MsgModifyStartTimeRequest, opts ...grpc.CallOption) (*MsgModifyStartTimeResponse, error)
	ModifyProjectInformation(ctx context.Context, in *MsgModifyProjectInformationRequest, opts ...grpc.CallOption) (*MsgModifyProjectInformationResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateProject(ctx context.Context, in *MsgCreateProjectRequest, opts ...grpc.CallOption) (*MsgCreateProjectResponse, error) {
	out := new(MsgCreateProjectResponse)
	err := c.cc.Invoke(ctx, "/notionallabs.anone.launchpad.Msg/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteProject(ctx context.Context, in *MsgDeleteProjectRequest, opts ...grpc.CallOption) (*MsgDeleteProjectResponse, error) {
	out := new(MsgDeleteProjectResponse)
	err := c.cc.Invoke(ctx, "/notionallabs.anone.launchpad.Msg/DeleteProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ModifyStartTime(ctx context.Context, in *MsgModifyStartTimeRequest, opts ...grpc.CallOption) (*MsgModifyStartTimeResponse, error) {
	out := new(MsgModifyStartTimeResponse)
	err := c.cc.Invoke(ctx, "/notionallabs.anone.launchpad.Msg/ModifyStartTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ModifyProjectInformation(ctx context.Context, in *MsgModifyProjectInformationRequest, opts ...grpc.CallOption) (*MsgModifyProjectInformationResponse, error) {
	out := new(MsgModifyProjectInformationResponse)
	err := c.cc.Invoke(ctx, "/notionallabs.anone.launchpad.Msg/ModifyProjectInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateProject(context.Context, *MsgCreateProjectRequest) (*MsgCreateProjectResponse, error)
	DeleteProject(context.Context, *MsgDeleteProjectRequest) (*MsgDeleteProjectResponse, error)
	ModifyStartTime(context.Context, *MsgModifyStartTimeRequest) (*MsgModifyStartTimeResponse, error)
	ModifyProjectInformation(context.Context, *MsgModifyProjectInformationRequest) (*MsgModifyProjectInformationResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateProject(ctx context.Context, req *MsgCreateProjectRequest) (*MsgCreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedMsgServer) DeleteProject(ctx context.Context, req *MsgDeleteProjectRequest) (*MsgDeleteProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (*UnimplementedMsgServer) ModifyStartTime(ctx context.Context, req *MsgModifyStartTimeRequest) (*MsgModifyStartTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyStartTime not implemented")
}
func (*UnimplementedMsgServer) ModifyProjectInformation(ctx context.Context, req *MsgModifyProjectInformationRequest) (*MsgModifyProjectInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyProjectInformation not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notionallabs.anone.launchpad.Msg/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateProject(ctx, req.(*MsgCreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notionallabs.anone.launchpad.Msg/DeleteProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteProject(ctx, req.(*MsgDeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ModifyStartTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgModifyStartTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ModifyStartTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notionallabs.anone.launchpad.Msg/ModifyStartTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ModifyStartTime(ctx, req.(*MsgModifyStartTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ModifyProjectInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgModifyProjectInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ModifyProjectInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notionallabs.anone.launchpad.Msg/ModifyProjectInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ModifyProjectInformation(ctx, req.(*MsgModifyProjectInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notionallabs.anone.launchpad.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _Msg_CreateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _Msg_DeleteProject_Handler,
		},
		{
			MethodName: "ModifyStartTime",
			Handler:    _Msg_ModifyStartTime_Handler,
		},
		{
			MethodName: "ModifyProjectInformation",
			Handler:    _Msg_ModifyProjectInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "launchpad/tx.proto",
}

func (m *MsgCreateProjectRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateProjectRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateProjectRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTx(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	if len(m.ProjectInformation) > 0 {
		i -= len(m.ProjectInformation)
		copy(dAtA[i:], m.ProjectInformation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ProjectInformation)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ProjectTitle) > 0 {
		i -= len(m.ProjectTitle)
		copy(dAtA[i:], m.ProjectTitle)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ProjectTitle)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateProjectResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateProjectResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateProjectResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProjectId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteProjectRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteProjectRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteProjectRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProjectId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteProjectResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteProjectResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteProjectResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgModifyStartTimeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgModifyStartTimeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgModifyStartTimeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTx(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if m.ProjectId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgModifyStartTimeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgModifyStartTimeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgModifyStartTimeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgModifyProjectInformationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgModifyProjectInformationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgModifyProjectInformationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProjectInformation) > 0 {
		i -= len(m.ProjectInformation)
		copy(dAtA[i:], m.ProjectInformation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ProjectInformation)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProjectId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgModifyProjectInformationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgModifyProjectInformationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgModifyProjectInformationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateProjectRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ProjectTitle)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ProjectInformation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreateProjectResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProjectId != 0 {
		n += 1 + sovTx(uint64(m.ProjectId))
	}
	return n
}

func (m *MsgDeleteProjectRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProjectId != 0 {
		n += 1 + sovTx(uint64(m.ProjectId))
	}
	return n
}

func (m *MsgDeleteProjectResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgModifyStartTimeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProjectId != 0 {
		n += 1 + sovTx(uint64(m.ProjectId))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgModifyStartTimeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgModifyProjectInformationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProjectId != 0 {
		n += 1 + sovTx(uint64(m.ProjectId))
	}
	l = len(m.ProjectInformation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgModifyProjectInformationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateProjectRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateProjectRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateProjectRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectTitle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectTitle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectInformation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectInformation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateProjectResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateProjectResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateProjectResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteProjectRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteProjectRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteProjectRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteProjectResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteProjectResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteProjectResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgModifyStartTimeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgModifyStartTimeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgModifyStartTimeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgModifyStartTimeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgModifyStartTimeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgModifyStartTimeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgModifyProjectInformationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgModifyProjectInformationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgModifyProjectInformationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectInformation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectInformation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgModifyProjectInformationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgModifyProjectInformationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgModifyProjectInformationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
