# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: anone-wasm.notional.ventures

on:
  push:
    branches: [ wasm-import ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Build the web
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        cd nft-marketplace
        npm ci --ignore-scripts
        npm run build
    
    - name: Transfer /dist folder to server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: nft-marketplace/dist
        remote: /root/anone-wasm.notional.ventures
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.PRIV_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
