// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ico/ico.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ICO struct {
	// Project unique id of each project
	ProjectId              uint64                                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" yaml:"project_id"`
	TokenForDistribution   types.Coin                             `protobuf:"bytes,2,opt,name=token_for_distribution,json=tokenForDistribution,proto3" json:"token_for_distribution" yaml:"token_for_distribution"`
	TotalDistributedAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=total_distributed_amount,json=totalDistributedAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_distributed_amount" yaml:"total_distributed_amount"`
	TokenListingPrice      github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=token_listing_price,json=tokenListingPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"token_listing_price" yaml:"token_listing_price"`
	PriceTokenDenom        string                                 `protobuf:"bytes,5,opt,name=price_token_denom,json=priceTokenDenom,proto3" json:"price_token_denom,omitempty" yaml:"price_token_denom"`
}

func (m *ICO) Reset()         { *m = ICO{} }
func (m *ICO) String() string { return proto.CompactTextString(m) }
func (*ICO) ProtoMessage()    {}
func (*ICO) Descriptor() ([]byte, []int) {
	return fileDescriptor_01997575a86e18b6, []int{0}
}
func (m *ICO) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ICO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ICO.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ICO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ICO.Merge(m, src)
}
func (m *ICO) XXX_Size() int {
	return m.Size()
}
func (m *ICO) XXX_DiscardUnknown() {
	xxx_messageInfo_ICO.DiscardUnknown(m)
}

var xxx_messageInfo_ICO proto.InternalMessageInfo

func (m *ICO) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *ICO) GetTokenForDistribution() types.Coin {
	if m != nil {
		return m.TokenForDistribution
	}
	return types.Coin{}
}

func (m *ICO) GetPriceTokenDenom() string {
	if m != nil {
		return m.PriceTokenDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*ICO)(nil), "notionallabs.anone.ico.ICO")
}

func init() { proto.RegisterFile("ico/ico.proto", fileDescriptor_01997575a86e18b6) }

var fileDescriptor_01997575a86e18b6 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x8b, 0xd3, 0x40,
	0x18, 0xed, 0xb8, 0x55, 0xd8, 0x11, 0x91, 0xc6, 0xb5, 0xc4, 0xa2, 0x49, 0x09, 0x28, 0x45, 0xd8,
	0x19, 0x56, 0x3d, 0x79, 0xb3, 0x5b, 0xc4, 0xc2, 0x82, 0x1a, 0x3c, 0x79, 0x09, 0x93, 0xc9, 0x58,
	0xc7, 0x4d, 0xe6, 0x2b, 0x99, 0xe9, 0xe2, 0x82, 0x7f, 0x40, 0xbc, 0xf8, 0xb3, 0xf6, 0xb8, 0x47,
	0xf1, 0x10, 0xa4, 0xfd, 0x07, 0xf9, 0x05, 0x32, 0x33, 0x2d, 0xad, 0xb2, 0x97, 0x3d, 0x25, 0x79,
	0xef, 0xe5, 0xbd, 0x97, 0xc9, 0xc3, 0x77, 0x24, 0x07, 0x2a, 0x39, 0x90, 0x79, 0x0d, 0x06, 0x82,
	0xbe, 0x02, 0x23, 0x41, 0xb1, 0xb2, 0x64, 0xb9, 0x26, 0x4c, 0x81, 0x12, 0x44, 0x72, 0x18, 0x1c,
	0xcc, 0x60, 0x06, 0x4e, 0x42, 0xed, 0x9d, 0x57, 0x0f, 0x22, 0x0e, 0xba, 0x02, 0x4d, 0x73, 0xa6,
	0x05, 0x3d, 0x3b, 0xca, 0x85, 0x61, 0x47, 0x94, 0x83, 0x54, 0x9e, 0x4f, 0xbe, 0x77, 0xf1, 0xde,
	0xf4, 0xf8, 0x6d, 0xf0, 0x02, 0xe3, 0x79, 0x0d, 0x5f, 0x04, 0x37, 0x99, 0x2c, 0x42, 0x34, 0x44,
	0xa3, 0xee, 0xf8, 0x7e, 0xdb, 0xc4, 0xbd, 0x73, 0x56, 0x95, 0x2f, 0x93, 0x2d, 0x97, 0xa4, 0xfb,
	0xeb, 0x87, 0x69, 0x11, 0x9c, 0xe1, 0xbe, 0x81, 0x53, 0xa1, 0xb2, 0x4f, 0x50, 0x67, 0x85, 0xd4,
	0xa6, 0x96, 0xf9, 0xc2, 0xb6, 0x0b, 0x6f, 0x0c, 0xd1, 0xe8, 0xf6, 0xb3, 0x07, 0xc4, 0xc7, 0x13,
	0x1b, 0x4f, 0xd6, 0xf1, 0xe4, 0x18, 0xa4, 0x1a, 0x3f, 0xbe, 0x68, 0xe2, 0x4e, 0xdb, 0xc4, 0x8f,
	0x7c, 0xc0, 0xd5, 0x36, 0x49, 0x7a, 0xe0, 0x88, 0xd7, 0x50, 0x4f, 0x76, 0xe0, 0xe0, 0x07, 0xc2,
	0xa1, 0x01, 0xc3, 0xca, 0xad, 0x5a, 0x14, 0x19, 0xab, 0x60, 0xa1, 0x4c, 0xb8, 0x37, 0x44, 0xa3,
	0xfd, 0xf1, 0x7b, 0xeb, 0xff, 0xbb, 0x89, 0x9f, 0xcc, 0xa4, 0xf9, 0xbc, 0xc8, 0x09, 0x87, 0x8a,
	0xae, 0xcf, 0xc2, 0x5f, 0x0e, 0x75, 0x71, 0x4a, 0xcd, 0xf9, 0x5c, 0x68, 0x32, 0x55, 0xa6, 0x6d,
	0xe2, 0x78, 0xd3, 0xe4, 0x6a, 0xdf, 0x24, 0xed, 0x3b, 0x6a, 0xb2, 0x65, 0x5e, 0x39, 0x22, 0xf8,
	0x86, 0xef, 0xf9, 0xfa, 0xa5, 0xd4, 0x46, 0xaa, 0x59, 0x36, 0xaf, 0x25, 0x17, 0x61, 0xd7, 0xf5,
	0x38, 0xb9, 0x76, 0x8f, 0xc1, 0xee, 0x89, 0xfc, 0x63, 0x99, 0xa4, 0x3d, 0x87, 0x9e, 0x78, 0xf0,
	0x9d, 0xc5, 0x82, 0x37, 0xb8, 0xe7, 0xc8, 0xcc, 0xbf, 0x50, 0x08, 0x05, 0x55, 0x78, 0xd3, 0x65,
	0x3f, 0x6c, 0x9b, 0x38, 0xdc, 0xfc, 0xc0, 0xff, 0x24, 0x49, 0x7a, 0xd7, 0x61, 0x1f, 0x2c, 0x34,
	0xb1, 0xc8, 0x78, 0x72, 0xb1, 0x8c, 0xd0, 0xe5, 0x32, 0x42, 0x7f, 0x96, 0x11, 0xfa, 0xb9, 0x8a,
	0x3a, 0x97, 0xab, 0xa8, 0xf3, 0x6b, 0x15, 0x75, 0x3e, 0x3e, 0xdd, 0x29, 0xbf, 0x99, 0xdf, 0xa1,
	0xdd, 0x1f, 0x75, 0xfb, 0xa3, 0x5f, 0xed, 0x3e, 0xfd, 0x47, 0xe4, 0xb7, 0xdc, 0xb0, 0x9e, 0xff,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xee, 0x4f, 0x16, 0xb7, 0x02, 0x00, 0x00,
}

func (m *ICO) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ICO) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ICO) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PriceTokenDenom) > 0 {
		i -= len(m.PriceTokenDenom)
		copy(dAtA[i:], m.PriceTokenDenom)
		i = encodeVarintIco(dAtA, i, uint64(len(m.PriceTokenDenom)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.TokenListingPrice.Size()
		i -= size
		if _, err := m.TokenListingPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIco(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.TotalDistributedAmount.Size()
		i -= size
		if _, err := m.TotalDistributedAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIco(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.TokenForDistribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIco(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.ProjectId != 0 {
		i = encodeVarintIco(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintIco(dAtA []byte, offset int, v uint64) int {
	offset -= sovIco(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ICO) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProjectId != 0 {
		n += 1 + sovIco(uint64(m.ProjectId))
	}
	l = m.TokenForDistribution.Size()
	n += 1 + l + sovIco(uint64(l))
	l = m.TotalDistributedAmount.Size()
	n += 1 + l + sovIco(uint64(l))
	l = m.TokenListingPrice.Size()
	n += 1 + l + sovIco(uint64(l))
	l = len(m.PriceTokenDenom)
	if l > 0 {
		n += 1 + l + sovIco(uint64(l))
	}
	return n
}

func sovIco(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIco(x uint64) (n int) {
	return sovIco(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ICO) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIco
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ICO: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ICO: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIco
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenForDistribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIco
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIco
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIco
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenForDistribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDistributedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIco
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIco
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIco
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalDistributedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenListingPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIco
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIco
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIco
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenListingPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceTokenDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIco
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIco
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIco
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceTokenDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIco(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIco
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIco(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIco
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIco
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIco
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIco
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIco
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIco
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIco        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIco          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIco = fmt.Errorf("proto: unexpected end of group")
)
